# Generated by Django 4.0.3 on 2022-05-07 19:31

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='tel',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sender',
            field=models.EmailField(max_length=254, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Subject'),
        ),
    ]
