# Generated by Django 4.0.3 on 2022-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_tel_alter_feedback_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tel',
            field=models.CharField(default='', max_length=10, verbose_name='Phone'),
        ),
    ]
