# Generated by Django 4.0.3 on 2022-05-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_email_alter_feedback_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
